-- Create reminders table
create table "public"."reminders" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "entity_type" text not null,
    "entity_id" bigint not null,
    "trigger_type" text not null,
    "trigger_date" timestamp with time zone not null,
    "action_text" text not null,
    "description" text,
    "priority" text not null default 'medium',
    "status" text not null default 'pending',
    "notify_user_ids" bigint[]
);

alter table "public"."reminders" enable row level security;

CREATE UNIQUE INDEX "reminders_pkey" ON public."reminders" USING btree (id);

-- Index for efficient queries
CREATE INDEX "reminders_trigger_date_idx" ON public."reminders" USING btree (trigger_date);
CREATE INDEX "reminders_status_idx" ON public."reminders" USING btree (status);

alter table "public"."reminders" add constraint "reminders_pkey" PRIMARY KEY using index "reminders_pkey";

alter table "public"."reminders" add constraint "reminders_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES sales(id) not valid;

alter table "public"."reminders" validate constraint "reminders_sales_id_fkey";

-- Grant permissions
grant delete on table "public"."reminders" to "authenticated";
grant insert on table "public"."reminders" to "authenticated";
grant select on table "public"."reminders" to "authenticated";
grant update on table "public"."reminders" to "authenticated";

grant delete on table "public"."reminders" to "service_role";
grant insert on table "public"."reminders" to "service_role";
grant references on table "public"."reminders" to "service_role";
grant select on table "public"."reminders" to "service_role";
grant trigger on table "public"."reminders" to "service_role";
grant truncate on table "public"."reminders" to "service_role";
grant update on table "public"."reminders" to "service_role";

-- Create policies
create policy "Enable insert for authenticated users only"
on "public"."reminders"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable read access for authenticated users"
on "public"."reminders"
as permissive
for select
to authenticated
using (true);

create policy "Reminders Update Policy"
on "public"."reminders"
as permissive
for update
to authenticated
using (true);

create policy "Reminders Delete Policy"
on "public"."reminders"
as permissive
for delete
to authenticated
using (true);

