-- =============================================================================
-- Migration 003: Gmail integration, discovery enrichment, communication tracking
-- =============================================================================

-- =============================================================================
-- 1. Email accounts (Gmail OAuth tokens)
-- =============================================================================
create table "public"."email_accounts" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "email_address" text not null,
    "access_token" text not null,
    "refresh_token" text not null,
    "token_expires_at" timestamp with time zone,
    "last_sync_history_id" text,
    "last_synced_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."email_accounts" enable row level security;

CREATE UNIQUE INDEX email_accounts_pkey ON public.email_accounts USING btree (id);
alter table "public"."email_accounts" add constraint "email_accounts_pkey" PRIMARY KEY using index "email_accounts_pkey";

CREATE UNIQUE INDEX email_accounts_email_address_key ON public.email_accounts USING btree (email_address);
alter table "public"."email_accounts" add constraint "email_accounts_email_address_key" UNIQUE using index "email_accounts_email_address_key";

alter table "public"."email_accounts" add constraint "email_accounts_sales_id_fkey"
    FOREIGN KEY (sales_id) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."email_accounts" validate constraint "email_accounts_sales_id_fkey";

-- =============================================================================
-- 2. Discovery prospects: add phone, website, status columns
-- =============================================================================
alter table "public"."discovery_prospects" add column if not exists "phone" text;
alter table "public"."discovery_prospects" add column if not exists "website" text;
alter table "public"."discovery_prospects" add column if not exists "status" text not null default 'pending';

-- =============================================================================
-- 3. Communication log: add external_id and subject for email tracking
-- =============================================================================
alter table "public"."communication_log" add column if not exists "external_id" text;
alter table "public"."communication_log" add column if not exists "subject" text;

CREATE INDEX IF NOT EXISTS communication_log_external_id_idx ON public.communication_log USING btree (external_id);

-- =============================================================================
-- 4. Campaign sends: add tracking_id for open/click tracking
-- =============================================================================
alter table "public"."campaign_sends" add column if not exists "tracking_id" uuid default gen_random_uuid();

-- =============================================================================
-- 5. RLS policies for email_accounts
-- =============================================================================
create policy "Users can view own email accounts"
    on "public"."email_accounts"
    for select
    using (true);

create policy "Users can insert own email accounts"
    on "public"."email_accounts"
    for insert
    with check (true);

create policy "Users can update own email accounts"
    on "public"."email_accounts"
    for update
    using (true);

create policy "Users can delete own email accounts"
    on "public"."email_accounts"
    for delete
    using (true);
