-- Create workflows table for persistent workflow automation
create table if not exists public.workflows (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  trigger jsonb not null,
  action jsonb not null,
  enabled boolean not null default true,
  sales_id bigint references public.sales(id),
  created_at timestamptz not null default now()
);

alter table public.workflows enable row level security;

create policy "Authenticated users can read workflows"
  on public.workflows for select
  to authenticated
  using (true);

create policy "Authenticated users can insert workflows"
  on public.workflows for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update workflows"
  on public.workflows for update
  to authenticated
  using (true);

create policy "Authenticated users can delete workflows"
  on public.workflows for delete
  to authenticated
  using (true);
