-- Property Units, Unit Documents, deal.unit_id, contacts.lead_type,
-- dealInteractions.amount/offer_status, and contacts_summary view update.

-- =============================================================================
-- 1. Property Units
-- =============================================================================
CREATE TABLE IF NOT EXISTS "public"."property_units" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "project_id" bigint NOT NULL,
    "code" text NOT NULL,
    "typology" text,
    "floor" integer,
    "orientation" text,
    "square_meters" numeric,
    "rooms" integer,
    "bathrooms" integer,
    "energy_class" text,
    "base_price" numeric,
    "current_price" numeric,
    "discount_pct" numeric DEFAULT 0,
    "status" text NOT NULL DEFAULT 'disponibile',
    "description" text,
    "features" jsonb DEFAULT '[]'::jsonb,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "public"."property_units" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS property_units_pkey ON public.property_units USING btree (id);
DO $$ BEGIN
  ALTER TABLE "public"."property_units" ADD CONSTRAINT "property_units_pkey" PRIMARY KEY USING INDEX "property_units_pkey";
EXCEPTION WHEN others THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE "public"."property_units" ADD CONSTRAINT "property_units_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE POLICY "property_units_select" ON "public"."property_units" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "property_units_insert" ON "public"."property_units" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "property_units_update" ON "public"."property_units" AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "property_units_delete" ON "public"."property_units" AS PERMISSIVE FOR DELETE TO authenticated USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."property_units" TO "authenticated";
GRANT ALL ON TABLE "public"."property_units" TO "service_role";

-- =============================================================================
-- 2. Unit Documents
-- =============================================================================
CREATE TABLE IF NOT EXISTS "public"."unit_documents" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "unit_id" bigint NOT NULL,
    "title" text NOT NULL,
    "doc_type" text,
    "file_path" text NOT NULL,
    "file_type" text,
    "created_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "public"."unit_documents" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS unit_documents_pkey ON public.unit_documents USING btree (id);
DO $$ BEGIN
  ALTER TABLE "public"."unit_documents" ADD CONSTRAINT "unit_documents_pkey" PRIMARY KEY USING INDEX "unit_documents_pkey";
EXCEPTION WHEN others THEN NULL;
END $$;
DO $$ BEGIN
  ALTER TABLE "public"."unit_documents" ADD CONSTRAINT "unit_documents_unit_id_fkey"
    FOREIGN KEY (unit_id) REFERENCES property_units(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE POLICY "unit_documents_select" ON "public"."unit_documents" AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "unit_documents_insert" ON "public"."unit_documents" AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "unit_documents_update" ON "public"."unit_documents" AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "unit_documents_delete" ON "public"."unit_documents" AS PERMISSIVE FOR DELETE TO authenticated USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."unit_documents" TO "authenticated";
GRANT ALL ON TABLE "public"."unit_documents" TO "service_role";

-- =============================================================================
-- 3. Add unit_id to deals
-- =============================================================================
ALTER TABLE "public"."deals" ADD COLUMN IF NOT EXISTS "unit_id" bigint;
DO $$ BEGIN
  ALTER TABLE "public"."deals" ADD CONSTRAINT "deals_unit_id_fkey"
    FOREIGN KEY (unit_id) REFERENCES property_units(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =============================================================================
-- 4. Add lead_type to contacts
-- =============================================================================
ALTER TABLE "public"."contacts" ADD COLUMN IF NOT EXISTS "lead_type" text;

-- =============================================================================
-- 5. Add amount and offer_status to dealInteractions
-- =============================================================================
ALTER TABLE "public"."dealInteractions" ADD COLUMN IF NOT EXISTS "amount" numeric;
ALTER TABLE "public"."dealInteractions" ADD COLUMN IF NOT EXISTS "offer_status" text;

-- =============================================================================
-- 6. Recreate contacts_summary view to include lead_type
-- =============================================================================
DROP VIEW IF EXISTS contacts_summary;

CREATE VIEW contacts_summary AS
SELECT
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.email_jsonb,
    jsonb_path_query_array(co.email_jsonb, '$[*].email')::text AS email_fts,
    co.phone_jsonb,
    jsonb_path_query_array(co.phone_jsonb, '$[*].number')::text AS phone_fts,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.lead_type,
    c.name AS company_name,
    count(DISTINCT t.id) AS nb_tasks
FROM
    contacts co
LEFT JOIN
    tasks t ON co.id = t.contact_id
LEFT JOIN
    companies c ON co.company_id = c.id
GROUP BY
    co.id, c.name;

-- Grant on the view
GRANT SELECT ON contacts_summary TO authenticated;
GRANT SELECT ON contacts_summary TO service_role;

-- =============================================================================
-- 7. Storage bucket for unit documents
-- =============================================================================
INSERT INTO storage.buckets (id, name, public) VALUES ('unit-documents', 'unit-documents', false) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "unit_docs_select" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'unit-documents');
CREATE POLICY "unit_docs_insert" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'unit-documents');
CREATE POLICY "unit_docs_delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'unit-documents');
