-- Foundation migration: projects, pipelines, RBAC, segments, conversations,
-- knowledge base (pgvector), bookings, discovery, campaigns, templates,
-- communication log.

-- =============================================================================
-- 1. pgvector extension
-- =============================================================================
create extension if not exists vector with schema extensions;

-- =============================================================================
-- 2. RBAC: migrate sales.administrator boolean → sales.role enum
-- =============================================================================
do $$ begin
  create type public.user_role as enum ('admin','manager','agent','read_only');
exception when duplicate_object then null;
end $$;

alter table "public"."sales" add column if not exists "role" public.user_role not null default 'agent';

-- Back-fill from existing boolean
update "public"."sales"
set role = case when administrator then 'admin'::public.user_role else 'agent'::public.user_role end
where role = 'agent'::public.user_role;

-- =============================================================================
-- 3. Projects
-- =============================================================================
create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "slug" text not null,
    "description" text,
    "location" text,
    "location_lat" double precision,
    "location_lng" double precision,
    "status" text not null default 'active',
    "config" jsonb default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."projects" enable row level security;

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);
CREATE UNIQUE INDEX projects_slug_key ON public.projects USING btree (slug);

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";
alter table "public"."projects" add constraint "projects_slug_key" UNIQUE using index "projects_slug_key";

-- =============================================================================
-- 4. Project pipelines
-- =============================================================================
create table "public"."project_pipelines" (
    "id" bigint generated by default as identity not null,
    "project_id" bigint not null,
    "stage_name" text not null,
    "stage_order" integer not null default 0,
    "is_terminal" boolean not null default false
);

alter table "public"."project_pipelines" enable row level security;

CREATE UNIQUE INDEX project_pipelines_pkey ON public.project_pipelines USING btree (id);

alter table "public"."project_pipelines" add constraint "project_pipelines_pkey" PRIMARY KEY using index "project_pipelines_pkey";

alter table "public"."project_pipelines" add constraint "project_pipelines_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."project_pipelines" validate constraint "project_pipelines_project_id_fkey";

-- =============================================================================
-- 5. Add project_id to deals (nullable for backward compat)
-- =============================================================================
alter table "public"."deals" add column if not exists "project_id" bigint;

alter table "public"."deals" add constraint "deals_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."deals" validate constraint "deals_project_id_fkey";

-- =============================================================================
-- 6. Segments
-- =============================================================================
create table "public"."segments" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "project_id" bigint,
    "criteria" jsonb not null default '[]'::jsonb,
    "auto_refresh" boolean not null default false,
    "last_refreshed_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "sales_id" bigint
);

alter table "public"."segments" enable row level security;

CREATE UNIQUE INDEX segments_pkey ON public.segments USING btree (id);
alter table "public"."segments" add constraint "segments_pkey" PRIMARY KEY using index "segments_pkey";

alter table "public"."segments" add constraint "segments_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."segments" validate constraint "segments_project_id_fkey";

alter table "public"."segments" add constraint "segments_sales_id_fkey"
    FOREIGN KEY (sales_id) REFERENCES sales(id) not valid;
alter table "public"."segments" validate constraint "segments_sales_id_fkey";

-- =============================================================================
-- 7. Segment contacts (materialized membership)
-- =============================================================================
create table "public"."segment_contacts" (
    "segment_id" bigint not null,
    "contact_id" bigint not null,
    "added_at" timestamp with time zone not null default now()
);

alter table "public"."segment_contacts" enable row level security;

CREATE UNIQUE INDEX segment_contacts_pkey ON public.segment_contacts USING btree (segment_id, contact_id);
alter table "public"."segment_contacts" add constraint "segment_contacts_pkey" PRIMARY KEY using index "segment_contacts_pkey";

alter table "public"."segment_contacts" add constraint "segment_contacts_segment_id_fkey"
    FOREIGN KEY (segment_id) REFERENCES segments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."segment_contacts" validate constraint "segment_contacts_segment_id_fkey";

alter table "public"."segment_contacts" add constraint "segment_contacts_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."segment_contacts" validate constraint "segment_contacts_contact_id_fkey";

-- =============================================================================
-- 8. Conversations
-- =============================================================================
create table "public"."conversations" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint,
    "project_id" bigint,
    "channel" text not null default 'web_chat',
    "status" text not null default 'active',
    "assigned_sales_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."conversations" enable row level security;

CREATE UNIQUE INDEX conversations_pkey ON public.conversations USING btree (id);
alter table "public"."conversations" add constraint "conversations_pkey" PRIMARY KEY using index "conversations_pkey";

alter table "public"."conversations" add constraint "conversations_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."conversations" validate constraint "conversations_contact_id_fkey";

alter table "public"."conversations" add constraint "conversations_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."conversations" validate constraint "conversations_project_id_fkey";

alter table "public"."conversations" add constraint "conversations_assigned_sales_id_fkey"
    FOREIGN KEY (assigned_sales_id) REFERENCES sales(id) not valid;
alter table "public"."conversations" validate constraint "conversations_assigned_sales_id_fkey";

-- =============================================================================
-- 9. Messages
-- =============================================================================
create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "conversation_id" bigint not null,
    "sender_type" text not null default 'contact',
    "content" text not null,
    "metadata" jsonb default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."messages" enable row level security;

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);
alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."messages" add constraint "messages_conversation_id_fkey"
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."messages" validate constraint "messages_conversation_id_fkey";

-- =============================================================================
-- 10. Knowledge documents
-- =============================================================================
create table "public"."knowledge_documents" (
    "id" bigint generated by default as identity not null,
    "project_id" bigint not null,
    "title" text not null,
    "file_path" text not null,
    "file_type" text,
    "status" text not null default 'pending',
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."knowledge_documents" enable row level security;

CREATE UNIQUE INDEX knowledge_documents_pkey ON public.knowledge_documents USING btree (id);
alter table "public"."knowledge_documents" add constraint "knowledge_documents_pkey" PRIMARY KEY using index "knowledge_documents_pkey";

alter table "public"."knowledge_documents" add constraint "knowledge_documents_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."knowledge_documents" validate constraint "knowledge_documents_project_id_fkey";

-- =============================================================================
-- 11. Document chunks (pgvector embeddings)
-- =============================================================================
create table "public"."document_chunks" (
    "id" bigint generated by default as identity not null,
    "document_id" bigint not null,
    "content" text not null,
    "embedding" extensions.vector(1536),
    "chunk_index" integer not null default 0
);

alter table "public"."document_chunks" enable row level security;

CREATE UNIQUE INDEX document_chunks_pkey ON public.document_chunks USING btree (id);
alter table "public"."document_chunks" add constraint "document_chunks_pkey" PRIMARY KEY using index "document_chunks_pkey";

alter table "public"."document_chunks" add constraint "document_chunks_document_id_fkey"
    FOREIGN KEY (document_id) REFERENCES knowledge_documents(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."document_chunks" validate constraint "document_chunks_document_id_fkey";

-- Index for similarity search (HNSW works on empty tables, unlike IVFFlat)
CREATE INDEX document_chunks_embedding_idx ON public.document_chunks
    USING hnsw (embedding extensions.vector_cosine_ops);

-- =============================================================================
-- 12. Bookings
-- =============================================================================
create table "public"."bookings" (
    "id" bigint generated by default as identity not null,
    "conversation_id" bigint,
    "contact_id" bigint,
    "sales_id" bigint,
    "calcom_event_id" text,
    "scheduled_at" timestamp with time zone,
    "status" text not null default 'pending',
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."bookings" enable row level security;

CREATE UNIQUE INDEX bookings_pkey ON public.bookings USING btree (id);
alter table "public"."bookings" add constraint "bookings_pkey" PRIMARY KEY using index "bookings_pkey";

alter table "public"."bookings" add constraint "bookings_conversation_id_fkey"
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."bookings" validate constraint "bookings_conversation_id_fkey";

alter table "public"."bookings" add constraint "bookings_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."bookings" validate constraint "bookings_contact_id_fkey";

alter table "public"."bookings" add constraint "bookings_sales_id_fkey"
    FOREIGN KEY (sales_id) REFERENCES sales(id) not valid;
alter table "public"."bookings" validate constraint "bookings_sales_id_fkey";

-- =============================================================================
-- 13. Discovery scans
-- =============================================================================
create table "public"."discovery_scans" (
    "id" bigint generated by default as identity not null,
    "project_id" bigint not null,
    "center_lat" double precision not null,
    "center_lng" double precision not null,
    "radius_km" double precision not null default 10,
    "target_sectors" text[] default '{}',
    "scoring_criteria" jsonb default '{}'::jsonb,
    "status" text not null default 'pending',
    "created_at" timestamp with time zone not null default now(),
    "completed_at" timestamp with time zone
);

alter table "public"."discovery_scans" enable row level security;

CREATE UNIQUE INDEX discovery_scans_pkey ON public.discovery_scans USING btree (id);
alter table "public"."discovery_scans" add constraint "discovery_scans_pkey" PRIMARY KEY using index "discovery_scans_pkey";

alter table "public"."discovery_scans" add constraint "discovery_scans_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."discovery_scans" validate constraint "discovery_scans_project_id_fkey";

-- =============================================================================
-- 14. Discovery prospects
-- =============================================================================
create table "public"."discovery_prospects" (
    "id" bigint generated by default as identity not null,
    "scan_id" bigint not null,
    "project_id" bigint not null,
    "business_name" text not null,
    "industry" text,
    "address" text,
    "lat" double precision,
    "lng" double precision,
    "size_employees" integer,
    "revenue_estimate" numeric,
    "key_contacts" jsonb default '[]'::jsonb,
    "score" integer default 0,
    "score_explanation" text,
    "source" text,
    "contact_id" bigint,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."discovery_prospects" enable row level security;

CREATE UNIQUE INDEX discovery_prospects_pkey ON public.discovery_prospects USING btree (id);
alter table "public"."discovery_prospects" add constraint "discovery_prospects_pkey" PRIMARY KEY using index "discovery_prospects_pkey";

alter table "public"."discovery_prospects" add constraint "discovery_prospects_scan_id_fkey"
    FOREIGN KEY (scan_id) REFERENCES discovery_scans(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."discovery_prospects" validate constraint "discovery_prospects_scan_id_fkey";

alter table "public"."discovery_prospects" add constraint "discovery_prospects_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."discovery_prospects" validate constraint "discovery_prospects_project_id_fkey";

alter table "public"."discovery_prospects" add constraint "discovery_prospects_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."discovery_prospects" validate constraint "discovery_prospects_contact_id_fkey";

-- =============================================================================
-- 15. Campaigns
-- =============================================================================
create table "public"."campaigns" (
    "id" bigint generated by default as identity not null,
    "project_id" bigint,
    "name" text not null,
    "segment_id" bigint,
    "status" text not null default 'draft',
    "channel" text not null default 'email',
    "created_at" timestamp with time zone not null default now(),
    "scheduled_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "sales_id" bigint
);

alter table "public"."campaigns" enable row level security;

CREATE UNIQUE INDEX campaigns_pkey ON public.campaigns USING btree (id);
alter table "public"."campaigns" add constraint "campaigns_pkey" PRIMARY KEY using index "campaigns_pkey";

alter table "public"."campaigns" add constraint "campaigns_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."campaigns" validate constraint "campaigns_project_id_fkey";

alter table "public"."campaigns" add constraint "campaigns_segment_id_fkey"
    FOREIGN KEY (segment_id) REFERENCES segments(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."campaigns" validate constraint "campaigns_segment_id_fkey";

alter table "public"."campaigns" add constraint "campaigns_sales_id_fkey"
    FOREIGN KEY (sales_id) REFERENCES sales(id) not valid;
alter table "public"."campaigns" validate constraint "campaigns_sales_id_fkey";

-- =============================================================================
-- 16. Campaign steps
-- =============================================================================
create table "public"."campaign_steps" (
    "id" bigint generated by default as identity not null,
    "campaign_id" bigint not null,
    "step_order" integer not null default 0,
    "channel" text not null default 'email',
    "template_content" jsonb default '{}'::jsonb,
    "delay_hours" integer not null default 0,
    "condition" jsonb default '{}'::jsonb
);

alter table "public"."campaign_steps" enable row level security;

CREATE UNIQUE INDEX campaign_steps_pkey ON public.campaign_steps USING btree (id);
alter table "public"."campaign_steps" add constraint "campaign_steps_pkey" PRIMARY KEY using index "campaign_steps_pkey";

alter table "public"."campaign_steps" add constraint "campaign_steps_campaign_id_fkey"
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."campaign_steps" validate constraint "campaign_steps_campaign_id_fkey";

-- =============================================================================
-- 17. Campaign sends
-- =============================================================================
create table "public"."campaign_sends" (
    "id" bigint generated by default as identity not null,
    "campaign_id" bigint not null,
    "step_id" bigint,
    "contact_id" bigint not null,
    "channel" text not null,
    "status" text not null default 'pending',
    "sent_at" timestamp with time zone,
    "delivered_at" timestamp with time zone,
    "opened_at" timestamp with time zone,
    "clicked_at" timestamp with time zone,
    "external_id" text
);

alter table "public"."campaign_sends" enable row level security;

CREATE UNIQUE INDEX campaign_sends_pkey ON public.campaign_sends USING btree (id);
alter table "public"."campaign_sends" add constraint "campaign_sends_pkey" PRIMARY KEY using index "campaign_sends_pkey";

alter table "public"."campaign_sends" add constraint "campaign_sends_campaign_id_fkey"
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."campaign_sends" validate constraint "campaign_sends_campaign_id_fkey";

alter table "public"."campaign_sends" add constraint "campaign_sends_step_id_fkey"
    FOREIGN KEY (step_id) REFERENCES campaign_steps(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."campaign_sends" validate constraint "campaign_sends_step_id_fkey";

alter table "public"."campaign_sends" add constraint "campaign_sends_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."campaign_sends" validate constraint "campaign_sends_contact_id_fkey";

-- =============================================================================
-- 18. Templates
-- =============================================================================
create table "public"."templates" (
    "id" bigint generated by default as identity not null,
    "project_id" bigint,
    "name" text not null,
    "channel" text not null default 'email',
    "subject" text,
    "body" text not null default '',
    "variables" jsonb default '[]'::jsonb,
    "created_at" timestamp with time zone not null default now(),
    "sales_id" bigint
);

alter table "public"."templates" enable row level security;

CREATE UNIQUE INDEX templates_pkey ON public.templates USING btree (id);
alter table "public"."templates" add constraint "templates_pkey" PRIMARY KEY using index "templates_pkey";

alter table "public"."templates" add constraint "templates_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."templates" validate constraint "templates_project_id_fkey";

alter table "public"."templates" add constraint "templates_sales_id_fkey"
    FOREIGN KEY (sales_id) REFERENCES sales(id) not valid;
alter table "public"."templates" validate constraint "templates_sales_id_fkey";

-- =============================================================================
-- 19. Communication log (unified timeline)
-- =============================================================================
create table "public"."communication_log" (
    "id" bigint generated by default as identity not null,
    "contact_id" bigint,
    "project_id" bigint,
    "channel" text not null,
    "direction" text not null default 'inbound',
    "content_summary" text,
    "metadata" jsonb default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."communication_log" enable row level security;

CREATE UNIQUE INDEX communication_log_pkey ON public.communication_log USING btree (id);
alter table "public"."communication_log" add constraint "communication_log_pkey" PRIMARY KEY using index "communication_log_pkey";

alter table "public"."communication_log" add constraint "communication_log_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."communication_log" validate constraint "communication_log_contact_id_fkey";

alter table "public"."communication_log" add constraint "communication_log_project_id_fkey"
    FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."communication_log" validate constraint "communication_log_project_id_fkey";

CREATE INDEX communication_log_contact_id_idx ON public.communication_log USING btree (contact_id);
CREATE INDEX communication_log_created_at_idx ON public.communication_log USING btree (created_at DESC);

-- =============================================================================
-- 20. Storage bucket for knowledge base
-- =============================================================================
insert into storage.buckets (id, name, public)
values ('knowledge', 'knowledge', false)
on conflict (id) do nothing;

CREATE POLICY "Knowledge select" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'knowledge');
CREATE POLICY "Knowledge insert" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'knowledge');
CREATE POLICY "Knowledge delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'knowledge');

-- =============================================================================
-- 21. Grants: authenticated + service_role for every new table
-- =============================================================================

-- projects
grant select, insert, update, delete on table "public"."projects" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."projects" to "service_role";

-- project_pipelines
grant select, insert, update, delete on table "public"."project_pipelines" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."project_pipelines" to "service_role";

-- segments
grant select, insert, update, delete on table "public"."segments" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."segments" to "service_role";

-- segment_contacts
grant select, insert, update, delete on table "public"."segment_contacts" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."segment_contacts" to "service_role";

-- conversations
grant select, insert, update, delete on table "public"."conversations" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."conversations" to "service_role";

-- messages
grant select, insert, update, delete on table "public"."messages" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."messages" to "service_role";

-- knowledge_documents
grant select, insert, update, delete on table "public"."knowledge_documents" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."knowledge_documents" to "service_role";

-- document_chunks
grant select, insert, update, delete on table "public"."document_chunks" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."document_chunks" to "service_role";

-- bookings
grant select, insert, update, delete on table "public"."bookings" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."bookings" to "service_role";

-- discovery_scans
grant select, insert, update, delete on table "public"."discovery_scans" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."discovery_scans" to "service_role";

-- discovery_prospects
grant select, insert, update, delete on table "public"."discovery_prospects" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."discovery_prospects" to "service_role";

-- campaigns
grant select, insert, update, delete on table "public"."campaigns" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."campaigns" to "service_role";

-- campaign_steps
grant select, insert, update, delete on table "public"."campaign_steps" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."campaign_steps" to "service_role";

-- campaign_sends
grant select, insert, update, delete on table "public"."campaign_sends" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."campaign_sends" to "service_role";

-- templates
grant select, insert, update, delete on table "public"."templates" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."templates" to "service_role";

-- communication_log
grant select, insert, update, delete on table "public"."communication_log" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."communication_log" to "service_role";

-- =============================================================================
-- 22. RLS policies for every new table (permissive, same pattern as existing)
-- =============================================================================

-- Helper: macro pattern for standard CRUD policies
-- projects
create policy "Enable insert for authenticated users only" on "public"."projects" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."projects" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."projects" as permissive for update to authenticated using (true) with check (true);
create policy "Projects Delete Policy" on "public"."projects" as permissive for delete to authenticated using (true);

-- project_pipelines
create policy "Enable insert for authenticated users only" on "public"."project_pipelines" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."project_pipelines" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."project_pipelines" as permissive for update to authenticated using (true) with check (true);
create policy "Project Pipelines Delete Policy" on "public"."project_pipelines" as permissive for delete to authenticated using (true);

-- segments
create policy "Enable insert for authenticated users only" on "public"."segments" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."segments" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."segments" as permissive for update to authenticated using (true) with check (true);
create policy "Segments Delete Policy" on "public"."segments" as permissive for delete to authenticated using (true);

-- segment_contacts
create policy "Enable insert for authenticated users only" on "public"."segment_contacts" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."segment_contacts" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."segment_contacts" as permissive for update to authenticated using (true) with check (true);
create policy "Segment Contacts Delete Policy" on "public"."segment_contacts" as permissive for delete to authenticated using (true);

-- conversations
create policy "Enable insert for authenticated users only" on "public"."conversations" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."conversations" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."conversations" as permissive for update to authenticated using (true) with check (true);
create policy "Conversations Delete Policy" on "public"."conversations" as permissive for delete to authenticated using (true);

-- messages
create policy "Enable insert for authenticated users only" on "public"."messages" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."messages" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."messages" as permissive for update to authenticated using (true) with check (true);
create policy "Messages Delete Policy" on "public"."messages" as permissive for delete to authenticated using (true);

-- knowledge_documents
create policy "Enable insert for authenticated users only" on "public"."knowledge_documents" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."knowledge_documents" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."knowledge_documents" as permissive for update to authenticated using (true) with check (true);
create policy "Knowledge Documents Delete Policy" on "public"."knowledge_documents" as permissive for delete to authenticated using (true);

-- document_chunks
create policy "Enable insert for authenticated users only" on "public"."document_chunks" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."document_chunks" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."document_chunks" as permissive for update to authenticated using (true) with check (true);
create policy "Document Chunks Delete Policy" on "public"."document_chunks" as permissive for delete to authenticated using (true);

-- bookings
create policy "Enable insert for authenticated users only" on "public"."bookings" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."bookings" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."bookings" as permissive for update to authenticated using (true) with check (true);
create policy "Bookings Delete Policy" on "public"."bookings" as permissive for delete to authenticated using (true);

-- discovery_scans
create policy "Enable insert for authenticated users only" on "public"."discovery_scans" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."discovery_scans" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."discovery_scans" as permissive for update to authenticated using (true) with check (true);
create policy "Discovery Scans Delete Policy" on "public"."discovery_scans" as permissive for delete to authenticated using (true);

-- discovery_prospects
create policy "Enable insert for authenticated users only" on "public"."discovery_prospects" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."discovery_prospects" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."discovery_prospects" as permissive for update to authenticated using (true) with check (true);
create policy "Discovery Prospects Delete Policy" on "public"."discovery_prospects" as permissive for delete to authenticated using (true);

-- campaigns
create policy "Enable insert for authenticated users only" on "public"."campaigns" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."campaigns" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."campaigns" as permissive for update to authenticated using (true) with check (true);
create policy "Campaigns Delete Policy" on "public"."campaigns" as permissive for delete to authenticated using (true);

-- campaign_steps
create policy "Enable insert for authenticated users only" on "public"."campaign_steps" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."campaign_steps" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."campaign_steps" as permissive for update to authenticated using (true) with check (true);
create policy "Campaign Steps Delete Policy" on "public"."campaign_steps" as permissive for delete to authenticated using (true);

-- campaign_sends
create policy "Enable insert for authenticated users only" on "public"."campaign_sends" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."campaign_sends" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."campaign_sends" as permissive for update to authenticated using (true) with check (true);
create policy "Campaign Sends Delete Policy" on "public"."campaign_sends" as permissive for delete to authenticated using (true);

-- templates
create policy "Enable insert for authenticated users only" on "public"."templates" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."templates" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."templates" as permissive for update to authenticated using (true) with check (true);
create policy "Templates Delete Policy" on "public"."templates" as permissive for delete to authenticated using (true);

-- communication_log
create policy "Enable insert for authenticated users only" on "public"."communication_log" as permissive for insert to authenticated with check (true);
create policy "Enable read access for authenticated users" on "public"."communication_log" as permissive for select to authenticated using (true);
create policy "Enable update for authenticated users only" on "public"."communication_log" as permissive for update to authenticated using (true) with check (true);
create policy "Communication Log Delete Policy" on "public"."communication_log" as permissive for delete to authenticated using (true);

-- =============================================================================
-- 23. Similarity search function for RAG
-- =============================================================================
create or replace function match_document_chunks(
    query_embedding extensions.vector(1536),
    match_threshold float default 0.7,
    match_count int default 5,
    filter_project_id bigint default null
)
returns table (
    id bigint,
    document_id bigint,
    content text,
    similarity float
)
language plpgsql
as $$
begin
    return query
    select
        dc.id,
        dc.document_id,
        dc.content,
        1 - (dc.embedding <=> query_embedding) as similarity
    from document_chunks dc
    join knowledge_documents kd on kd.id = dc.document_id
    where
        (filter_project_id is null or kd.project_id = filter_project_id)
        and 1 - (dc.embedding <=> query_embedding) > match_threshold
    order by dc.embedding <=> query_embedding
    limit match_count;
end;
$$;
