name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Show npm version
        run: npm -v

      - name: Configure npm for faster installs
        run: |
          npm config set fund false
          npm config set audit false
          npm config set progress false
          npm config set fetch-retries 3
          npm config set fetch-timeout 120000

      - name: Install dependencies (clean)
        run: npm ci --prefer-offline --no-audit --no-fund --legacy-peer-deps
        env:
          CI: 'true'

      - name: Typecheck
        run: npm run -s typecheck || echo "Skipping typecheck if not defined"

      - name: Lint
        run: npm run -s lint || echo "Skipping lint if not defined"

      - name: Build
        run: npm run -s build


